name = "nexusdesk-api"
compatibility_date = "2024-01-15"
main = "src/worker.ts"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "prod-d1-tutorial"
database_id = "d155fcab-6f9d-4eed-82f1-87c43b20a35d"

[vars]
ENVIRONMENT = "production"